 services:
   db:
     image: mysql:latest
     container_name: recipe-db
     environment:
       MYSQL_DATABASE: 'recipe'
       MYSQL_USER: 'user'
       MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
     volumes:
       - .mysql_data:/var/lib/mysql
   app:
     image: amiriddin/recipe-django
     ports:
       - 8000:8000
     volumes:
       - .:/app
     container_name: recipe_container
     command: python manage.py runserver 0.0.0.0:8000
     depends_on:
       - db
 volumes:
   mysql_data: