# Generated by Django 4.2.1 on 2023-07-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_imagesrecipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesrecipes',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
