# Generated by Django 4.2.1 on 2023-07-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_imagesrecipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesrecipes',
            name='image',
            field=models.FileField(default='images/unkown-profile.jpg', upload_to='images/'),
        ),
    ]
