# Generated by Django 4.2.1 on 2023-07-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='ingredient',
        ),
    ]
