# Generated by Django 4.2.1 on 2023-07-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesRecipes',
        ),
    ]
