# Generated by Django 4.2.1 on 2023-07-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_delete_imagesrecipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
