# Generated by Django 4.2.1 on 2023-07-09 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_alter_recipeowner_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesRecipesOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='unkown-profile.jpg', null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeowner',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='recipeowner',
            name='image_hash',
        ),
        migrations.RemoveField(
            model_name='recipeowner',
            name='recipe_id',
        ),
        migrations.DeleteModel(
            name='ImagesRecipes',
        ),
        migrations.DeleteModel(
            name='RecipeOwner',
        ),
    ]
