# Generated by Django 4.2.1 on 2023-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_remove_recipes_url_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesrecipesowner',
            name='image',
            field=models.FileField(default='unkown-profile.jpg', null=True, upload_to='images/recipe/'),
        ),
    ]
