# Generated by Django 4.2.1 on 2023-07-15 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0017_alter_imagesrecipesowner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesrecipesowner',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racipe', to=settings.AUTH_USER_MODEL),
        ),
    ]
