# Generated by Django 4.1 on 2022-10-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notebook", "0002_item_text_delete_block2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="update",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
