# Generated by Django 4.2.1 on 2023-07-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
