# Generated by Django 4.2.1 on 2023-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio_user',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
