# Generated by Django 4.2.1 on 2023-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_alter_profile_bio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='unkown-profile.jpg', null=True, upload_to='images/profile-pic/'),
        ),
    ]
