# Generated by Django 4.2.1 on 2023-07-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
